#FROM maven:3.8.6-openjdk:17-jdk-slim AS build
#WORKDIR C:\Jatin\Spring\learnSpring\in28minutes spring-microservices-v3 main 91.docker-hello-world-java
#COPY . C:\Jatin\Spring\learnSpring\in28minutes spring-microservices-v3 main 91.docker-hello-world-java\
#RUN mvn -f C:\Jatin\Spring\learnSpring\in28minutes spring-microservices-v3 main 91.docker-hello-world-java\pom.xml clean package

#FROM openjdk:17-jdk-slim
#EXPOSE 5000
#COPY --from=build C:\Jatin\Spring\learnSpring\in28minutes spring-microservices-v3 main 91.docker-hello-world-java\target\*.jar app.jar
#ENTRYPOINT ["sh", "-c", "java -jar /app.jar"]

#FROM maven:3.8.6-openjdk-18-slim AS build
#WORKDIR /home/app
#COPY . /home/app
#RUN mvn -f /home/app/pom.xml clean package

#FROM openjdk:18.0-slim
#EXPOSE 5000
#COPY --from=build /home/app/target/*.jar app.jar
#ENTRYPOINT [ "sh", "-c", "java -jar /app.jar" ]

FROM maven:3.8.6-openjdk-18-slim AS build
WORKDIR /home/app

COPY ./pom.xml /home/app/pom.xml
COPY ./src/main/java/com/in28minutes/rest/webservices/restfulwebservices/RestfulWebServicesApplication.java	/home/app/src/main/java/com/in28minutes/rest/webservices/restfulwebservices/RestfulWebServicesApplication.java

RUN mvn -f /home/app/pom.xml clean package

COPY . /home/app
RUN mvn -f /home/app/pom.xml clean package

FROM openjdk:18.0-slim
EXPOSE 5000
COPY --from=build /home/app/target/*.jar app.jar
ENTRYPOINT [ "sh", "-c", "java -jar /app.jar" ]